version: '3.9'

services:
  event_db:
    image: postgres:15-bullseye
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - 6900:5432
    networks:
      - event_net
    deploy:  
      resources:
        limits:
          cpus: '0.2'
          memory: 300M

  event:
    build: .
    environment:
      GUNICORN: false
    volumes:
      - .:/usr/app
    ports:
      - 6950:80
    networks:
      - event_net
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 300M
    depends_on:
      event_db:
        condition: service_started

networks:
  event_net:
    driver: bridge
    name: event_net