apiVersion: apps/v1
kind: Deployment
metadata:
  name: event
  labels:
    app: event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
        - name: event
          image: my-app-image
          resources:
            limits:
              memory: "100Mi"
              cpu: "0.2"
            requests:
              memory: "100Mi"
              cpu: "0.2"
          ports:
            - containerPort: 80
          imagePullPolicy: Always

          env:
            - name: "AUTH_HOST"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: AUTH_HOST
            - name: "AUTH_PATH_AUTH"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: AUTH_PATH_AUTH
            - name: "AUTH_PORT"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: AUTH_PORT

            - name: "EVENT_DB_USER"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: EVENT_DB_USER
            - name: "EVENT_DB_HOST"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: EVENT_DB_HOST
            - name: "EVENT_DB_NAME"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: EVENT_DB_NAME
            - name: "EVENT_DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: EVENT_DB_PASSWORD
            - name: "EVENT_DB_PORT"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: EVENT_DB_PORT



---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: event-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 80
    type: HTTP
    requestPath: /event/ping